### ISSUE TITLE
Rely on fsp, how to add "tls" stack in e2 studio

### ISSUE THREAD

**Issue by cyliangtw** [renesas/fsp#1]
Hi,
   I installed setup_fspv0_8_0_e2s_v7_6_0.exe to evaluate e2 + fsp.
In https://www.renesas.com/us/en/products/software-tools/software-os-middleware-driver/software-package/ra-fsp.html, it mentioned **"Provides easy connectivity options to major cloud providers"**, though I could add "FreeRTOS+TCP" in stack configuration of e2, I still can't find any stack of "TLS" or "cloud".

How to add "tls" stack in e2 studio, even cloud for AWS_IoT connection ?

**Comment by warren-renesas** [comment]
This question has been posted on and will be answered from the Renesas Rulz RA Forum here:
https://renesasrulz.com/ra/f/forum/15308/how-to-add-tls-stack-in-e2-studio
