### ISSUE TITLE
2 ADC Stacks cause warning: "ADC_DMAC_CHANNELS_PER_BLOCK_NULL" redefined

### ISSUE THREAD

**Issue by jachimop** [renesas/fsp#103]
I am using the FSP Configurator (for RA6M5) with 2 ADC Stacks to generate the code for my project and there is an issue with ADC_DMAC_CHANNELS_PER_BLOCK_NULL macro defined twice in hal_data.h with different values.

**Comment by kjassmann-renesas** [comment]
Thank you for reporting this. We will fix it in our next release.
