### ISSUE TITLE
Missing enum constant for ADC channel (RA6M5)

### ISSUE THREAD

**Issue by jachimop** [renesas/fsp#104]
I wanted to use
`fsp_err_t R_ADC_Read (adc_ctrl_t * p_ctrl, adc_channel_t const reg_id, uint16_t * const p_data)`
function to read from AN128 (unit 1) channel, but it seems that the corresponding enum constant is missing in `adc_channel_t` .

```
typedef enum e_adc_channel
{
    ...
    ADC_CHANNEL_26          = 26,      ///< ADC channel 26
    ADC_CHANNEL_27          = 27,      ///< ADC channel 27
    ADC_CHANNEL_DUPLEX_A    = 50,      ///< Data duplexing register A
    ...
} adc_channel_t;
```
The last channel is ADC_CHANNEL_27 = 27, but I need ADC_CHANNEL_28 = 28, which can be transformed to 0x10000000 mask, which is one of the valid channels according to:
`#define BSP_FEATURE_ADC_UNIT_1_CHANNELS                   (0x1FFF0007) // 0 to 2, 16 to 28`

**Comment by kjassmann-renesas** [comment]
Thank you for reporting this. It will be fixed in the next release.
