### ISSUE TITLE
Unable to configure ADC1 interrupts to trigger DMA

### ISSUE THREAD

**Issue by iYak99** [renesas/fsp#105]
"RA Smart Configurator 3.1.0", unable to configure a DMA with "ADC1 SCAN END" (or any ADC1) interrupts as a trigger for EK-RA6M2.

![image](https://user-images.githubusercontent.com/54155080/129223758-ed32432c-6dec-49f2-b663-b7faa499d106.png)

**Comment by renesas-brandon-hussey** [comment]
The list of Activation Sources is dynamically generated based on the modules you have added to your project. It appears you have added the r_adc module and have it configured for Unit 0. That is why you see the ADC0 sources. If you change the Unit to 1 in the r_adc properties

![image](https://user-images.githubusercontent.com/55763142/129226702-4962ede7-e20b-46a1-a74c-bbb97c9f6095.png)

then you should see ADC1 SCAN END in the DMAC Activation Source list.

![image](https://user-images.githubusercontent.com/55763142/129226939-103706a7-103f-4d8d-9c77-d9a574cc55ec.png)

**Comment by iYak99** [comment]
Thanks!
