### ISSUE TITLE
USB PCDC 

### ISSUE THREAD

**Issue by rmatris** [renesas/fsp#114]
R_USB_DataSizeGet returns datasize of 0xffffffd0 (or variants of large numbers) when sending greater than 1 byte of data at a time.
![renesas](https://user-images.githubusercontent.com/16060545/131715283-efbc4841-0a9c-446b-b539-4be555606996.png)

This seems to be related to the code below. 
r_usb_pcdc_driver.c
usb_pcdc_read_complete: 
ctrl.data_size = mess->read_req_len - mess->tranlen; << results in a negative value or large unsigned value.

**Comment by rmatris** [comment]
The read size is not updated when calling R_USB_Read.
In the example project "USB_PCDC_EK_RA4M2_EP",  case USB_STATUS_CONFIGURED is always hit first which reads out 8 bytes.
When case USB_STATUS_READ_COMPLETE is hit, the readsize is not updated, and is set to the old/previous value of 8.

**Comment by TakahiroMuranaka** [comment]
Please do not use the instance variable "_**g_basic0_ctrl**_" when getting the received size.

Please get the received size as follow.

![image](https://user-images.githubusercontent.com/80372555/131970050-ca673488-2190-4536-a21a-6a9c55272700.png)
