### ISSUE TITLE
RA2L1 LPM_Open side effects to unexpected going stanbdby

### ISSUE THREAD

**Issue by alexrayne** [renesas/fsp#119]
Hallo!
works with RA2L1 FSP3.2

use LPM_open to configure chip for standby with later R_LPM_LowPowerModeEnter .  but going into standby happens unexpected not in R_LPM_LowPowerModeEnter, but in other routine, that some waits with __WFI. 

this happens, since LPM_open configures SSBY for standby. So any successive WFI will down cpu. But semantic of LPM API expects that sleepdown happens on invoke R_LPM_LowPowerModeEnter. So, imho, SSBY should configures there (in LowPowerModeEnter), not in Open.

**Comment by kjassmann-renesas** [comment]
Resolution: This behavior can be enabled with the new `Standby Limit` configuration in v3.5.0.

https://renesas.github.io/fsp/group___l_p_m.html#:~:text=in%20the%20build.-,Standby%20Limit,-Enabled
