### ISSUE TITLE
Add SPI examples using SPI Mode

### ISSUE THREAD

**Issue by dsabol-ammcoats** [renesas/fsp#135]
The current SPI examples use Clock Synchronous Mode, but do there are no examples using SPI Mode.

SPI Mode requires the chip select line, and there are some things to be wary of when using the chip select and the FSP, so it would be helpful to have an example using that.  I would expect most people using the FSP for an SPI driver use SPI Mode and not Clock Synchronous Mode.

**Comment by renesas-brandon-hussey** [comment]
Hi @dsabol-ammcoats , which examples are you referring to? Is this for SPI master or slave? Is there a reason you're requesting more information on simple SPI mode? In SPI master mode I don't believe you would see a difference between the 2 modes unless you have multiple SPI masters on the bus.
