### ISSUE TITLE
IAR: C-SPY stack monitor plugin fix

### ISSUE THREAD

**Issue by felipe-iar** [renesas/fsp#138]
Hi friends @Renesas,

I bring a small but perhaps useful suggestion towards UX.

As per RASC/FSP v3.4.0, when using the _IAR C-SPY Debugger_ along the RA's startup code and linker configuration, the `stack monitor plugin` does not function as expected.

This issue was already resolved before during the Synergy era (ref. __R11AN0195EU0100__, section 8). Since the RA's startup matches the situation found in Synergy, I believe that the same debugger initialization parameter could be potentially applied to the RA code generator itself, so the `<project>.ewd` would come up good-to-go for the main stack debugging, out-of-box.

The parameter is `--proc_stack_main=g_main_stack,g_main_stack+sizeof(g_main_stack)`.

I've seen that a vector table issue for achieving proper reset which was a workaround (#21) now is applied directly from the `RASC` application for new projects, which is great!

Would be possible to get the stack monitor initialization parameters for the IAR C-SPY Debugger out-of-box in the same way for the future versions of the `RASC`?

Thanks in advance.

**Comment by renesas-brandon-hussey** [comment]
@felipe-iar this feature has been accepted. It is currently scheduled to be released in Q1 2022 with FSP v3.6.0.

**Comment by felipe-iar** [comment]
@renesas-brandon-hussey this is great! Thanks for the update.
