### ISSUE TITLE
Int Configurator not relax IRQ group conflict after conflict resolved

### ISSUE THREAD

**Issue by alexrayne** [renesas/fsp#146]
Hallow!
Use RA2L1 chip project, and  have situation: group0 IRQ ocupied by comm stacks - 5 uarts, GPT timers, IRQ0 ...
1) append 1 more comm stack - SPI0
2) after that gor error about conflict on Interupts Config tab - IRQ0 in error state
3) delete SPI 0 driver from stacks.
4) after SPI0 IRQ free , IRQ0 keep on error state

expects that IRQ conflicts error should be relaxed after some comm stack driverr deleted, but actualy i need delete IRQ0 and append it again, to resolve error

**Comment by kjassmann-renesas** [comment]
Sorry, we have not been able to reproduce this issue. I followed the steps you described, and IRQ0 was restored to the Interrupts configuration tab as expected.

If you would like to share your project configuration.xml file showing this issue, please contact Renesas technical support.

Our Technical Support Contact Form is available in the Design & Support menu on www.renesas.com.
