### ISSUE TITLE
AES-256 CTR mode encryption takes twice as long when SCE9 hardware acceleration is enabled than w/o acceleration.

### ISSUE THREAD

**Issue by hwmaier** [renesas/fsp#147]
We did measure performance of the hardware accelerated encryption functions using the official FSP example [`NetX_crypto_ek_ra6m5_ep`](https://github.com/renesas/ra-fsp-examples/tree/master/example_projects/ek_ra6m5/NetX_crypto/NetX_crypto_ek_ra6m5_ep)

We found that disabling SCE9 hardware acceleration yielded a much faster encryption when using the `crypto_method_aes_ctr_256` method. The `NX_CRYPTO_ENCRYPT` operation takes 3691 CPU cycles **without** SCE9 hardware acceleration and 7322 CPU cycles (twice as long) when SCE9 hardware acceleration is enabled. 

We measured adding this instrumentation to file `aes_thread_entry.c` and we removed all other threads.

```
    /* Encryption. */
    ULONG cycles1 = *((ULONG *) 0xE0001004); // ARM DWT_CYCCNT cycle count register
    status = _nx_crypto_method_aes_operation (NX_CRYPTO_ENCRYPT, handler, &crypto_method_aes_ctr_256,
                                              (uint8_t*) key_ctr_256,
                                              crypto_method_aes_ctr_256.nx_crypto_key_size_in_bits,
                                              (uint8_t*) plain_ctr_256, sizeof(plain_ctr_256), (uint8_t*) iv_ctr_256,
                                              generated_ciphertext, sizeof(generated_ciphertext), metadata,
                                              metadata_size,
                                              NX_CRYPTO_NULL,
                                              NX_CRYPTO_NULL);
    ULONG cycles2 = *((ULONG *) 0xE0001004);  // ARM DWT_CYCCNT cycle count register
    SEGGER_RTT_printf(0, "** cycles: %lu\n", cycles2 - cycles1);
```

This comes to our surprise as we expected the opposite and wonder if there is maybe an issue with the  implementation?

Other encryption modes like AES_256_GCM and AES_256_CBC run substantially faster with SCE9 hardware acceleration.

**Comment by jritchey-renesas** [comment]
@hwmaier Confirmed you are correct that HW accelerated aes-ctr implementation is slower than the software implementation. The HW accelerated implementation is encrypting individual blocks. This has a lot of overhead because SCE9 procedures use wrapped keys that are being decrypted for every block. Thanks for making light of this, we will optimize this in an upcoming release.

**Comment by hwmaier** [comment]
Confirmed to be fixed, CTR is now 20 times faster with HW acceleration. Thank you.

**Comment by xianghui-renesas** [comment]
Hi, @hwmaier , is there any application level code update required to benefit from this fix? thanks!
