### ISSUE TITLE
SPI0 - r_spi as slave sending wrong output

### ISSUE THREAD

**Issue by nikosh42** [renesas/fsp#149]
Hi,

We use the Renesas RA to communicate with a FPGA via SPI. The FPGA is the master and the Renesas is the slave (SPI0 - r_spi). 
Board:   Custom User Board (Any Device) 
Device:  R7FA4M1AB2CLJ 
Toolchain:   GCC ARM Embedded 
Toolchain Version:   9.3.1.20200408 
FSP Version:   3.4.0 
 
MISO 100
MOSI 101
SCK  102
SS   103

The call 
fsp_err_t status = g_spi0.p_api->writeRead(g_spi0.p_ctrl,pCMD,from_fpga.Buffer,256,SPI_BIT_WIDTH_8_BITS)  should transfer 256Bytes in both directions.
The RA receive side works absolut correct, but the sending part is wrong. It looks like only the first byte comes out and all other data are wrong (0x00 or 0xFF).

NOTE: The same API call, Pins and the same SPI settings working great with the SCI0 (r_sci_spi). 
I double check this in both direction between (SPI0-r_spi and SCI0-r_sci_spi) changing PIN assignment and driver.

**Comment by kjassmann-renesas** [comment]
Please contact Renesas technical support for help isolating the cause of this issue.

Our Technical Support Contact Form is available in the Design & Support menu on www.renesas.com.
