### ISSUE TITLE
Many warnings occur due to FSP 

### ISSUE THREAD

**Issue by mertyilmaaz** [renesas/fsp#152]
The cause of the error is capital "İ" letter. The project files created by FSP has some capital "İ" letters and this results in many warnings, if corrected manually, warnings are eliminated.
And this capital "İ" letters are only included in ifndef preprocessor statements.
![image](https://user-images.githubusercontent.com/61128677/143778136-03fd74f2-b0ff-4705-a80d-f235dd787fb2.png)

**Comment by mertyilmaaz** [comment]
The problem is solved, if you face with the problem what you need to do is to change your windows display language to English. There may be alternative solutions, this is how I dealt with it.

**Comment by renesas-brandon-hussey** [comment]
@mertyilmaaz what was your display language set to previously?
