### ISSUE TITLE
Setting timer mode to one-shot does not result in MD set to one-shot

### ISSUE THREAD

**Issue by dlogan01** [renesas/fsp#155]
This issue is with Timer Driver on r_gpt. When selecting the Mode as one-shot in General settings, the MD bits in GTCR are not set to 001. They stay at the default value of 000. It would also be nice if toggle mode were set for GTIOA and GTIOB in GTIOR, since this has to be done for saw-wave one-shot pulse mode. (I was working on an RA2E1 when I discovered this issue, so I don't know if this issue exists on all RA parts.)

**Comment by kjassmann-renesas** [comment]
FSP one-shot mode generates a single pulse: https://renesas.github.io/fsp/group___g_p_t.html#:~:text=One%2DShot%20Mode%20Output

The GPT periodic one-shot (GTCR.MD = 001) feature is not yet supported. We will add support for this mode in a future release.
