### ISSUE TITLE
Failed install setup_fsp_v3_4_0_rasc_v2021-10.exe on windows7 x64

### ISSUE THREAD

**Issue by Femtometer** [renesas/fsp#156]
Install setup_fsp_v3_4_0_rasc_v2021-10.exe

![image](https://user-images.githubusercontent.com/5461891/144531720-5bd93265-e639-4f78-b458-93cab8687788.png)

**Comment by Femtometer** [comment]
Translation: Failed running this program, because this computer missing api-ms-win-core-path-l1-1-0.dll. Reinstall to sovle this problem.

**Comment by Femtometer** [comment]
Python 3.9+ does  not support win7, does this software use python?
https://superuser.com/questions/1660386/api-ms-win-core-path-l1-1-0-dll-is-missing-from-your-computer

**Comment by renesas-brandon-hussey** [comment]
HI @Femtometer , which operating system are you using? e2 studio 2021-10 requires Windows 8 or newer. This is documented in the release notes. 

https://www.renesas.com/us/en/document/rln/e-studio-2021-10-release-note?language=en&r=488826

**Comment by Femtometer** [comment]
@renesas-brandon-hussey I'm using Win7, Solved by copy folder from an installed computer.
