### ISSUE TITLE
ask question about hvnd for USBX

### ISSUE THREAD

**Issue by zhengjianxing** [renesas/fsp#165]
Hello, I would like to ask if your next version will produce an example of hvnd based on USBX?

**Comment by renesas-brandon-hussey** [comment]
Hi @zhengjianxing this will not be in our next release. I have sent this request to our Marketing team. They will prioritize it for a future release.

**Comment by renesas-brandon-hussey** [comment]
I checked with our USB software developer and am told that USBX still does not support HVND. There is no plan for this support to be added so I am closing this ticket.
