### ISSUE TITLE
Device Partition Tool Fails To Start in IAR EWARM and Keil MDK For RA Devices

### ISSUE THREAD

**Issue by kjassmann-renesas** [renesas/fsp#167]
## Issue

A problem has been noted when using the RA Standalone Configurator tool (RASC) with the IAR and Keil environments.

Creating and generating a project works as expected when using RASC. However, the Device Partition Manager fails to execute when launching a debug session or when selected from the Tools menu in IAR EWARM or Keil MDK.

For example:

![image](https://user-images.githubusercontent.com/31899442/146018803-dbdb63fc-56d2-4007-81dc-691a2b843537.png)

## Workaround

When IAR is used, disable the use of the .mac file on debug startup in the Project settings for the secure project (`Debugger` > `Setup` tab > uncheck `Use macro file(s)`).

![image](https://user-images.githubusercontent.com/31899442/147107883-65377ee8-d177-4cc9-8879-2668ec9c456e.png)

Launch the RASC tool and then open the Renesas Device Partition Manager (RPDM) from the menu item available in the user interface of RASC.

![image](https://user-images.githubusercontent.com/31899442/146017268-ac57a884-2bd3-469c-9a96-a24efd69959f.png)

Locate `RAM_S_SIZE`, `RAM_C_SIZE`, `FLASH_S_SIZE` and `FLASH_C_SIZE` in the .rpd file inside the \Debug\Exe folder. Convert these value to KB (divide by 0x400) to determine the partition sizes fields to enter in RDPM.

After configuring RPDM to set the desired TrustZone boundaries, click `Run` and verify the result is `SUCCESSFUL!`. If a connection error occurs, power cycle the target and run RPDM again.

Example .rpd file:
![image](https://user-images.githubusercontent.com/31899442/147108335-b716e370-3638-4eae-a662-56281bd6e5f0.png)

Associated TrustZone boundary settings in RPDM:
![image](https://user-images.githubusercontent.com/31899442/147108790-9ccccd52-b81b-4b93-9b09-1edf70e37b54.png)

**Comment by pyhalte** [comment]
I can can confirm this issue.

My tests with different FSP versions: 3.0.0 and 3.1.0 works, but 3.2.0, 3.3.0, and 3.5.0 does not work. Tested with IAR 9.10.1.

I also tested FSP 3.5.0 with IAR 9.20.2, but it also doesn't work.
