### ISSUE TITLE
The J-Link OB firmware can fail when downloading large binaries.

### ISSUE THREAD

**Issue by GodavarthyAravinda** [renesas/fsp#178]
## Issue
In some cases flash programming of RA devices fail resulting in errors when trying to launch a debug session in e2 studio.

This has been noticed when trying to program images greater than 128KB in size onto a board that have the updated builds of the S124 J-Link OB firmware.

**Note:**
 The original firmware build as programmed in the factory did not exhibit the problem, but the later builds supplied with and installed by SEGGER’s software packages did.

## Workaround

Follow the steps below to update the S124 J-Link OB firmware to J-Link v7.60d or newer to resolve the issue

1. Download and install J-Link v7.60d. from https://www.segger.com/downloads/jlink/
2. Navigate to the J-Link software install directory, typically  “C:\Program Files (x86)\SEGGER\JLink”.
3. Launch JLinkConfig.exe 
4. Select J-Link OB-S124 in JLinkConfig, right click and select "Update firmware"
5. After installing the new firmware, JLinkConfig should show the updated firmware build info

**Comment by perigoso** [comment]
Encountered this issue on a EK-RA4M3, with v7.62 it seems to not be present
