### ISSUE TITLE
MISRA C support

### ISSUE THREAD

**Issue by Simon-Thome** [renesas/fsp#184]
Would it be possible to add a few extra implementations to support MISRA C (IAR)?

There are a few inline functions in header files, that do not have a void parameter, which violates rule 8.1
example: __STATIC_INLINE bsp_unique_id_t const * R_BSP_UniqueIdGet (). 

Would it be possible to add the following to the header files?
#pragma system_include /* treat file as system include file for MISRA check */

**Comment by Simon-Thome** [comment]
I see what you mean. 
Maybe it would be best for now if you could just add the void, like this: __STATIC_INLINE bsp_unique_id_t const * R_BSP_UniqueIdGet (void)

**Comment by kjassmann-renesas** [comment]
Understood. I will create a ticket to check this rule throughout FSP.
