### ISSUE TITLE
IAR linker files with 2 identical memory_regions.icf files

### ISSUE THREAD

**Issue by pyhalte** [renesas/fsp#193]
There appears to be 3 .icf files on my project directory:

```
./memory_regions.icf
./script/memory_regions.icf
./script/fsp.icf
```

Those 2 memory_regions.icf files have the exact same content.

If I delete all three files, and then use Smart Configurator to regenerate project files, only following files are generated:

```
./memory_regions.icf
./script/fsp.icf
```

Now recompile fails because IAR cannot find memory_regions.icf, which presumably should be in ./script folder.

I suspect that this is an error in file generation and only ./script/memory_regions.icf should be created, and ./memory_regions.icf should not even exist.

Using FSP 3.6.0, but project was originally created with FSP 3.0.0 .

**Comment by renesas-brandon-hussey** [comment]
Hi @pyhalte thanks for the information. I'd like to verify your setup. Are you using the IAR compiler with e2 studio or are you using RASC with IAR Embedded Workbench? This sounds like RASC and IAR EW.

**Comment by pyhalte** [comment]
It is RASC with IAR EW. Installer was 'setup_fsp_v3_6_0_rasc_v2022-01.exe'.

**Comment by renesas-brandon-hussey** [comment]
It appears that IAR EW is getting out of sync with the RASC project. RASC communicates information to RASC using the buildinfo.ipcf file. The location of the memory_regions.icf file changed between FSP v3.0.0 and FSP v3.6.0 and it seems the new location is not being configured to be searched by the linker. A member of our Tools team will investigate this. For now, you should be able to work around this issue by adding `--config_search "$PROJ_DIR$"` to Linker >> Extra Options as shown below.

![image](https://user-images.githubusercontent.com/53097876/162767167-de6e7cc7-4fd6-4d7f-9bfc-2dec55cf91c1.png)
