### ISSUE TITLE
CapTouch QE "A variable used in this view was not found. Please refer to the help for this view."

### ISSUE THREAD

**Issue by arpadmozes** [renesas/fsp#197]
I am connected to the target through the J-link ARM debugger. I see that the communication status says connecting via OCD emulator, is it ok?
I cannot enable monitoring due to the error "A variable used in this view was not found."
I use fsp 2.3.

![image](https://user-images.githubusercontent.com/11389540/166905303-46150a9b-bf1c-4ab5-ae21-4b4c661c48c0.png)

![image](https://user-images.githubusercontent.com/11389540/166914352-adf4db2a-3055-480f-a1a2-deedfa270ad2.png)

**Comment by renesas-austin-hansen** [comment]
For future reference, a guide has been published to help users avoid issues with QE for CapTouch:
https://www.renesas.com/us/en/document/apn/using-qe-and-fsp-develop-capacitive-touch-applications
