### ISSUE TITLE
RA2E2: R_IIC_B_SLAVE_Open() does not return an error if slave address is in the range of reserved addresses.

### ISSUE THREAD

**Issue by muvicado** [renesas/fsp#203]
**Background:**
Using the EK-RA2E2 I3C slave sample code (i3c_slave_ek_ra2e2_ep), slave addresses appear to be restricted to the range specified in the Phillips  I2C-bus specification (https://www.nxp.com/docs/en/user-guide/UM10204.pdf page 16 3.1.12 Reserved addresses)
the I2C spec.  I found this out while re-implementing the Renesas FS2012 flow sensor to an RA2E2. The FS2012 uses slave address 0x07, which is outside of the restricted range. But the FS2012 has been in the market for some time. I presumed the address was okay to use, but discovered it is not, since 0x07 is in the range of reserved addresses (0000 XXX and 1111 XXX). Using a different I2C address outside the reserved range fixes my issue. I will use 0x17 instead.

**Bug:**
The bug I'm reporting is that the I2C driver for RA2E2 does not return an error when you use an invalid slave address. I think it should return an error. It would have saved me a lot of time. Note that I2C drivers for some of the RA MCUs (e.g. RA6M3 on EK-RA6M3, which I also tested) do not restrict the I2C slave address in this way. So that is inconsistent.
My guess is that it is because some RA FSP drivers for I2C slave are written for the "I2C Bus Interface (IIC)" peripheral (section 36 of RA6M3 User Manual), and others (e.g. in RA2E2 FSP support) are for the "I3C Bus Interface (I3C)" peripheral as in RA2E2 (which also supports I2C, but with the address restriction added). Assuming the I3C drivers are newer, perhaps they implemented slave address restriction from version 2 of the I2C spec, whereas the older I2C peripheral driver(s) did not. But I'm only guessing about that.

**Remedy:**
Though I now have a work-around, I think R_IIC_B_SLAVE_Open() call should return an error (perhaps FSP_ERR_INVALID_RATE) if the slave address is out of range. If that was the case, I would have tried other addresses and found the issue quite quickly and saved a lot of time.

**Not a bug:**
It also might be worth providing a mechanism to override the address restriction, for customers who are porting code from a legacy device that uses an address in the ranges 0000 XXX and 1111 XXX and do not have the flexibility to change the slave address as I did. This of course would just be a convenience. It cannot be seen as a bug.

_(reference: see https://en-support.renesas.com/ticket/350147)_
Note: It may also be a good idea to add a FAQ regarding this restriction, in case others (especially customers) encounter this issue.

**Comment by aniruddhabajaj-renesas** [comment]
Thanks for sharing the details. 
We will add a check for reserved addresses at the time of module configuration on e2studio.
