### ISSUE TITLE
E2 studio does not generate define needed to OSPI work in DMA mode

### ISSUE THREAD

**Issue by GluchowD** [renesas/fsp#228]
Hi,
I am working on a project using e2 studio (3.6, but I also tested it on 3.8) and RA6M5 MCU. I use a OSPI interface for RAM and Flash, When I enable DMA for OSPI Flash and generate configuration. The r_ospi_cfg.h file miss define OSPI_CFG_DMAC_SUPPORT_ENABLE (1). I have to use a DMA, because normal implementation is not robust when for example interrupt occur while writing operation is executed. Can I ask you to provide instructions on forcing the generation of this define?
![image](https://user-images.githubusercontent.com/92524590/184291429-a18d962c-af15-46ab-b3c8-7656c1741377.png)
![image](https://user-images.githubusercontent.com/92524590/184291478-ecd2dcb5-b87b-473d-bcdb-fefe6bb29b33.png)
![image](https://user-images.githubusercontent.com/92524590/184291392-84a33c62-151d-4bd3-91c6-0cce5e263726.png)

**Comment by renesas-austin-hansen** [comment]
Hi Dominik!  Global defines can be added by navigating to **Project -> Properties** then **C/C++ Build -> Settings**.  There should be an option to change the defines provided in toolchain commands there.  For example, this is what the window looks like for GCC:

![image](https://user-images.githubusercontent.com/65614784/184895882-e756b330-e87a-4c0a-be22-af196e4cec2d.png)

**Comment by renesas-brandon-hussey** [comment]
Hi @GluchowD , this is an issue where both OSPI Flash and OSPI RAM are attempting to create the r_ospi_cfg.h file. This is scheduled to be fixed in the next release of FSP.
