### ISSUE TITLE
flash_hp_df_erase() uses the wrong wait_count value

### ISSUE THREAD

**Issue by jadefds** [renesas/fsp#241]
flash_hp_df_erase() uses wait_count = p_ctrl->timeout_write_df instead of timeout_erase_df_block.

**Comment by jadefds** [comment]
Raised PR [#240](https://github.com/renesas/fsp/pull/240) with proposed change.

**Comment by renesas-austin-hansen** [comment]
This change will be part of the next FSP release.  Thank you for the fix!
