### ISSUE TITLE
Boot time from cold start too slow

### ISSUE THREAD

**Issue by moshidev** [renesas/fsp#264]
# Issue

If using FSP v4.3.0, when started the device from a cold start (disconnected from power and connected again), it takes 5 seconds to enter user's application code.

Don't know if it is related, but __bss_end__ shows some crazy values.

Using GNU cross compiler toolchain. It is independent of making the executable with or without debug simbols. Target: R7FA6M1AD3CFM.

# Workaround

Using e2studio 23-01 (last version) with FSP 4.1.0.

**Comment by renesas-brandon-hussey** [comment]
Hi @moshidev , yes that's far too long. That amount of time makes me wonder if the application is waiting for the sub-clock to stabilize which can take ~4 seconds. Default projects do not typically wait on that though. Could you share your project? If not, could you give us some more information on what you've done to your project after initial creation?

FYI, this type of question would normally be a better fit for the [official Renesas support forum](https://community.renesas.com/mcu-mpu/ra/f/forum) as this is likely related to the application. The FSP development team can check this issue but we will likely not be as fast as the forum. Thanks!
