### ISSUE TITLE
Flexible Software Package does not install properly on neither Ubuntu 20.04 nor 22.04

### ISSUE THREAD

**Issue by egdtg** [renesas/fsp#269]
As I understand it Ubuntu 20.04 is officially supported by FSP so I thought I'd give it a go. I downloaded the latest AppImage from the Releases-page and tried to install it on a fresh installation of Ubuntu 20.04 (plus all the updates from official channels). While the installation of FSP appears to successfully complete, the GCC toolchain fails to install and one cannot create a new project because you can't choose a toolchain (because none is installed!). Installing a toolchain manually from Help -> Add Renesas Toolchains doesn't work either, because it always fails with the error message:
```
Packate Install Result:
    Error running extract step
    type but be one of 'zip'
```

Installing the AppImage on Ubuntu 22.04 requires a little work. First, one needs to install libfuse2 as per this page:
[https://github.com/AppImage/AppImageKit/wiki/FUSE](https://github.com/AppImage/AppImageKit/wiki/FUSE)

Then, one needs to set the environment-variable GDK_BACKEND to x11 (because Wayland is default in Ubuntu 22.04), like so:
`GDK_BACKEND=x11 ./setup_fsp_v4_3_0_e2s_v2023-01.AppImage`

The end result is the same, however. No compiler gets installed. Can't install it manually either. Please advise!

**Comment by renesas-andyb** [comment]
Sorry for the problems you are seeing here. I believe that the FSP platform installer for the next release (due later this month) should resolve your issues.  Please let us know if this is not the case.

**Comment by egdtg** [comment]
Thank you! I'll give it a try once it's out. One more thing: regular support for Ubuntu 20.04 is ending this month, so if you haven't already done so please take the appropriate steps to make sure FSP works under Ubuntu 22.04.

Thanks again!
