### ISSUE TITLE
A bug in bsp_clocks.c

### ISSUE THREAD

**Issue by clint-k** [renesas/fsp#274]
I think I found a bug in bsp_clocks.c, line 375.

```
#elif defined(BSP_CFG_SDADC_CLOCK_SOURCE) && (BSP_CFG_SDADC_CLOCK_SOURCE == BSP_CLOCKS_SOURCE_MAIN_OSC)
 #define BSP_PRV_MAIN_OSC_USED                    (1)
#else
```
The rhs of the macro equation should be `BSP_CLOCKS_SOURCE_CLOCK_MAIN_OSC`. ("CLOCK" was missing.)
Currently, if the macro `BSP_CFG_SDADC_CLOCK_SOURCE` is defined with value 0, the equation asserts and `BSP_PRV_MAIN_OSC_USED` is defined with value 1. 
On RA2A1, this activates MOCO and makes impossible to use XTAL/EXTAL pins as GPIO or other peripheral function pins.

**Comment by SeanMeng0509** [comment]
Hi @clint-k, thank you for reporting this issue. We will get it fixed in the next release.
