### ISSUE TITLE
OSPI Driver Issues

### ISSUE THREAD

**Issue by pltmcu-jci** [renesas/fsp#283]
I'd like to highlight two issues (and potential fixes) I ran into while interfacing the RA6M5 with an octal flash memory device (ISSI [IS25LX256](https://www.issi.com/WW/pdf/25LX-WX256-128.pdf))

1. [`r_ospi_status_sub()`](https://github.com/renesas/fsp/blob/d52e5a6a59b7c638da860c2bb309b6e78e752ff8/ra/fsp/src/r_ospi/r_ospi.c#L847C9-L847C9) assumes 4 dummy clock cycles when reading the device status in not in extended SPI mode which may not work for all devices. Here's what I changed:
![image](https://github.com/renesas/fsp/assets/136373868/e3ea1fda-6a35-489c-b329-5f0d73e9310c)

2. [`r_ospi_direct_transfer()`](https://github.com/renesas/fsp/blob/d52e5a6a59b7c638da860c2bb309b6e78e752ff8/ra/fsp/src/r_ospi/r_ospi.c#L969)  assumes the byte order which may be incorrect. In my specific case, I needed the DOPI byte order to be byte0, byte1, byte2, byte3. The driver assumes the order setting to be byte1, byte0, byte3, byte2. I believe that this method needs to check the SPI protocol and the byte order then set it accordingly. Here's what I did in my case: 
![image](https://github.com/renesas/fsp/assets/136373868/4a658ae0-74fe-4b21-ab18-f602ebaa6e45)

**Comment by renesas-austin-hansen** [comment]
Thank you for reporting these issues.  We agree these settings should be configurable and are planning to make improvements in the upcoming FSP 5.0.0 release.
