### ISSUE TITLE
Renesas Smart Configurator generates invalid data for ACMPLP1

### ISSUE THREAD

**Issue by JAALFE** [renesas/fsp#3]
**Describe the bug**
Using the Renesas Smart Configurator for RA2A1 and creating a stack for low power analog comparator 1 result invalid data in config structure. 
If you select:
- CMPIN1 (channel 1 only) for Analog Input Voltage Source
- CMPREF1 (channel 1 only) for Reference Voltage Input Source

the generator selects a value from enum, which is not allowed for RA2A1 controller.
Also in initialisation function of FSP `R_ACMPLP_Open()` the value will be set wrong, because the driver will shift the value by 4.

**To Reproduce**
1. Open Renesas Smart Configurator
2. Create a new stack for low power analog comparator
3. Use following values:
![RSC_LPACMP_Settings](https://user-images.githubusercontent.com/63848569/79564331-bf473080-80ae-11ea-9ff9-36731fc225d7.PNG)

4. Press create
5. Check hal_data.c
![RSC_created_code](https://user-images.githubusercontent.com/63848569/79564536-2369f480-80af-11ea-8dd7-bf1842617a4c.PNG)

![RSC_defines](https://user-images.githubusercontent.com/63848569/79564553-2a910280-80af-11ea-8dac-10f95de19779.PNG)

**Expected behavior**
I think the value should be 1 and not 4, because the allowed register values of ACMPLP.COMP0SEL and ACMPLP.COMP1SEL are:
- 0b00
- 0b01
- 0b10

Also the value for channel 1 is shifted by 4 in initialisation routine.

**Desktop**
 - Windows 10 19093
 - RA Smart Configurator Version: 7.8.0.R20200321-2326
 - IAR Embedded Workbench for Arm 8.50.1

**Comment by warren-renesas** [comment]
Hi JAALFE-
We are supporting FSP and RA related issues using our support forum located here:
Support: https://renesasrulz.com/ra/f/forum

I will copy your issues to the forum and then will add the link in a comment below. You can then go to the forum to see the response.
http://renesasrulz.com/ra/f/forum/16109/renesas-smart-configurator-generates-invalid-data-for-acmplp1-3

**Comment by kamalk-renesas** [comment]
This issue is moved to support forum, hence closing it from GitHub.
