### ISSUE TITLE
Linker fails when used RA6 + ThreadX with Option -flto

### ISSUE THREAD

**Issue by sebastian-dev** [renesas/fsp#338]
Create a new C/C++ Project with any RA6 + ThreadX.
When you enable the Link Time Optimizer (-flto) in the options the linker fails with the error:
`../ra/fsp/src/rm_threadx_port/tx_thread_schedule.c:325:(.text.PendSV_Handler+0x68): undefined reference to _tx_port_wait_thread_ready'`

to fix this issue you have to change in tx_thread_schedule.c the function:
from:
`__attribute((weak)) void * _tx_port_wait_thread_ready (VOID)`
to
`__attribute((weak, used)) void * _tx_port_wait_thread_ready (VOID)`

**Comment by renesas-brandon-hussey** [comment]
This is being internally tracked using FSPRA-2284.
