### ISSUE TITLE
Ethernet example doesn't work after v5.3.0 on RA6M4

### ISSUE THREAD

**Issue by miyazakh** [renesas/fsp#368]
Run [an example here](https://github.com/renesas/ra-fsp-examples/tree/master/example_projects/ek_ra6m4/ethernet/ethernet_ek_ra6m4_ep) on fsp v5.3.0 and v5.4.0. Network cannot connect and shows `Network down` message from the example.

The example works with fsp v5.2.0.

**Comment by renesas-brandon-hussey** [comment]
Hi @miyazakh , this appears to be an application issue and would better submitted to the Renesas Engineering Community [here](https://community.renesas.com/mcu-mpu/ra/f/forum). Issues in this repository are for issues related to FSP code and there is not enough information in your post to know where the issue may be.
