### ISSUE TITLE
code for calc_iaq_2nd_gen()

### ISSUE THREAD

**Issue by FPGAy** [renesas/fsp#376]

**Comment by FPGAy** [comment]
Hi All,
I was looking at the ZMOD library and cant seem to find the source code for the function " `int8_t calc_iaq_2nd_gen(iaq_2nd_gen_handle_t *handle, const zmod4xxx_dev_t *dev,
                        const iaq_2nd_gen_inputs_t *algo_input,
                        iaq_2nd_gen_results_t *results);` "

I am being stupid right?

**Comment by renesas-austin-hansen** [comment]
Hi @FPGAy, ZMOD4xxx sensors' code is provided in a precompiled library (librm_zmod4xxx.a) as Renesas does not currently distribute the source.  Libraries are currently only provided via the artifacts for each FSP release.
