### ISSUE TITLE
Consecutive volatile float access instructions may be out of order when using Arm Compiler 6.22

### ISSUE THREAD

**Issue by renesas-austin-hansen** [renesas/fsp#377]
## Issue

The FSP development team has identified an issue with Arm Compiler 6.22 where in some cases the load and store instructions for consecutive volatile float accesses may be placed out-of-order.  Arm has been notified and a fix is tentatively scheduled for the AC 6.23 release.  **In FSP code, this issue only affects the IIRFA driver and only when Polling Mode is set to Disabled.**

## Workaround

- When using IIRFA with Arm Compiler 6.22 set **Polling Mode** to **Enabled.**
- Inspect any non-FSP code carefully after compilation to ensure volatile float access order is as expected.

**Comment by renesas-brandon-hussey** [comment]
This issue is listed as fixed in the [AC 6.23 release notes](https://developer.arm.com/documentation/109995/062300/Differences-from-previous-release/Defect-fixes/Compiler-and-integrated-assembler--armclang?lang=en).

> [SDCOMP-67544] When compiling for AArch32 state, the compiler could generate incorrect code for a volatile variable of a single-precision floating-point type. This has been fixed. 

The RA FSP team will test and verify.
