### ISSUE TITLE
FSP2.2.1 - no RA2L1 support in eclipse FSP configurator

### ISSUE THREAD

**Issue by alexrayne** [renesas/fsp#40]
Hallow!
have installed FSP 2.2.1 Packs on e2studio. 
Works with project on RA2A1-EK , and try to change device to RA2L1 - but Device selection have no RA2L1 devices.
how to install FSP 2.2.1 properly?

**Comment by renesas-brandon-hussey** [comment]
Hi Alex, e2 studio does not support migrating from the RA2A1 to the RA2L1. You will need to create a new project for the RA2L1 and migrate your application.

FYI, the official support forum for FSP is on [Renesas Rulz](https://renesasrulz.com/ra). We advise you create your tickets there for the quickest response.
