### ISSUE TITLE
VEEM can't define Reference data size > 0

### ISSUE THREAD

**Issue by alexrayne** [renesas/fsp#45]
Hallow!
works with RA2L1 project.
install VEEM on flash_lp.
enable reference data - it done well.
try set reference data size =2 - it not changes any way, always reset to 0.

is VEEM supports Reference data?

**Comment by jeremy-baker** [comment]
The value set for reference data size must be a multiple of 4 bytes, when reference data is enabled. This constraint is set in the XML for the VEE :- 

            <constraint display="Value must be a multiple of 4 bytes (Data flash program size).">("${module.middleware.rm_vee_flash.ref_data_size}" % 4) == 0</constraint>

However the text for this constraint doesn't doesn't actual get displayed, it would appear.
