### ISSUE TITLE
Problems in configuring sci_uart channel 1

### ISSUE THREAD

**Issue by zhengjianxing** [renesas/fsp#85]
ra6m4_ek, in applies-to-v3.0.0, freeRTOS project, i configuring sci_uart channel 1 and  invoking R_SCI_UART_Open (&g_uart1_ctrl, &g_uart1_cfg)，This will slow down the execution of the delay function vTaskDelay(). 
Please accept my English level.
![sci_uart1](https://user-images.githubusercontent.com/25891227/121628603-13c81f00-caac-11eb-9b41-366b72a86783.png)

**Comment by renesas-brandon-hussey** [comment]
Hi @zhengjianxing , can you provide information on how you are measuring the slow down? And how did you discover that r_sci_uart was causing this?

**Comment by zhengjianxing** [comment]
![nor](https://user-images.githubusercontent.com/25891227/121716458-a26f8700-cb12-11eb-9e82-867d221f4e2a.png)
![ab](https://user-images.githubusercontent.com/25891227/121716482-aac7c200-cb12-11eb-9d1a-e8fb4c0a91ad.png)

Created a FreeRTOS simple project, only a 100ms led flip task, did not invoking R_SCI_UART_Open (attention:UART channel 1)is normal, after invoking R_SCI_UART_Open , the LED flashing interval will be longer, as long as the timer (GPT, AGT) overflows, the interrupt mode is the same.

**Comment by zhengjianxing** [comment]
> Hi @zhengjianxing , can you provide information on how you are measuring the slow down? And how did you discover that r_sci_uart was causing this?

Reply as above

**Comment by zhengjianxing** [comment]
Sorry, it should be because the pin is occupied
![reson](https://user-images.githubusercontent.com/25891227/121766166-a9ce7900-cb82-11eb-96a6-627cfe58845d.png)
