### ISSUE TITLE
CMSIS-zone assignment error generating project with P002, P003, or P015 as analog input for RA6T1

### ISSUE THREAD

**Issue by mpenate-ellenbytech** [renesas/fsp#86]
Steps to reproduce:
1. Create a new RA project in e2 studio
2. Select MCU: R7FA6T1AD3CFM
3. Select bare metal project
4. Add an ADC stack in FSP configurator
5. Enable ADC0 in pin manager
6. Enable P002, P003 or P015 as analog pins in ADC0 pin manager
7. Attempt to generate in FSP configurator

**Comment by dlogan01** [comment]
I can recreate this CMSISS-Zone error with FSP 3.01. The error message also says "Slot name not found P002" (I picked P002 for AN02. I tried it on FSP 2.0.0-beta 1, and I did not get that error. It appears both the 64-pin parts have this problem. The 100-pin parts are fine.

**Comment by xianghui-renesas** [comment]
Hi, Marry,

I am planning to get there around 4pm +-15mins.

Would this be ok?

Thanks,
Xianghui
________________________________

**Comment by xianghui-renesas** [comment]
Hi, Marry,

I am so sorry I won't be able to pick up the package today. Could I pick it up tomorrow morning at around 9:30am?

Thanks,
Xianghui
________________________________

**Comment by garyj-renesas** [comment]
Verified fixed in the 3.1 RC internal release
