### ISSUE TITLE
RA2L1 IO registers absent NVIC view

### ISSUE THREAD

**Issue by alexrayne** [renesas/fsp#98]
Hallow!
FSP provides IO registers view for most if perifery, bu i have no any mentions about NVIC contets (and also SysTick)
inspecting NVIC via memory view is a hard trick, so provide NVIC in IO view would be great.

**Comment by kjassmann-renesas** [comment]
Thank you for the suggestion. We are investigating the changes required to include Arm Cortex-M registers in the e2 studio Registers view.

**Comment by renesas-austin-hansen** [comment]
Apologies for the delay in response; NVIC and SysTick registers were made available in the IO Registers view starting with FSP v3.0.0.
